### ISSUE TITLE
run PS的demo时触发OSError

### ISSUE THREAD

**Issue by BLue1881euLB** [Hsword/Hetu#35]
编译通过，单卡和allreduce都能正常run，
但是run PS模式的demo报了一个so的错误，
bash examples/cnn/scripts/hetu_2gpu_ps.sh mlp CIFAR10

报错如下,
Cluster: {
  Chief: localhost,
  Servers(1): {'localhost': 1},
  Workers(2): {'localhost': 2},
}
Process Process-1:
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/Hetu/bin/../python/runner.py", line 27, in start_sched
    ht.scheduler_init()
  File "/home/Hetu/python/hetu/gpu_ops/executor.py", line 106, in scheduler_init
    ps_comm = ll(path_to_lib("libps.so"))
  File "/home/anaconda3/lib/python3.8/ctypes/__init__.py", line 459, in LoadLibrary
    return self._dlltype(name)
  File "/home/anaconda3/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/Hetu/python/hetu/gpu_ops/../../../build/lib/libps.so: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E
Process Process-2:
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/Hetu/bin/../python/runner.py", line 33, in start_server
    ht.server_init()
  File "/home/Hetu/python/hetu/gpu_ops/executor.py", line 94, in server_init
    ps_comm = ll(path_to_lib("libps.so"))
  File "/home/anaconda3/lib/python3.8/ctypes/__init__.py", line 459, in LoadLibrary
    return self._dlltype(name)
  File "/home/anaconda3/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/Hetu/python/hetu/gpu_ops/../../../build/lib/libps.so: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E
[1,1]<stdout>:Building MLP model...
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "/home/Hetu/examples/cnn/scripts/../main.py", line 122, in <module>
[1,1]<stderr>:    executor = ht.Executor(eval_nodes, dist_strategy=strategy)
[1,1]<stderr>:  File "/home/Hetu/python/hetu/gpu_ops/executor.py", line 375, in __init__
[1,1]<stderr>:    config = HetuConfig(eval_node_list=all_eval_nodes,
[1,1]<stderr>:  File "/home/Hetu/python/hetu/gpu_ops/executor.py", line 247, in __init__
[1,1]<stderr>:    worker_init()
[1,1]<stderr>:  File "/home/Hetu/python/hetu/gpu_ops/executor.py", line 83, in worker_init
[1,1]<stderr>:    ps_comm = ll(path_to_lib("libps.so"))
[1,1]<stderr>:  File "/home/anaconda3/lib/python3.8/ctypes/__init__.py", line 459, in LoadLibrary
[1,1]<stderr>:    return self._dlltype(name)
[1,1]<stderr>:  File "/home/anaconda3/lib/python3.8/ctypes/__init__.py", line 381, in __init__
[1,1]<stderr>:    self._handle = _dlopen(self._name, mode)
[1,1]<stderr>:OSError: /home/Hetu/python/hetu/gpu_ops/../../../build/lib/libps.so: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "/home/Hetu/python/hetu/gpu_ops/executor.py", line 507, in __del__
[1,1]<stderr>:    if self.config.comp_stream is not None:
[1,1]<stderr>:AttributeError: 'Executor' object has no attribute 'config'
[1,0]<stderr>:Exception ignored in: <function Executor.__del__ at 0x7f8772777700>
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "/home/Hetu/python/hetu/gpu_ops/executor.py", line 507, in __del__
[1,0]<stderr>:    if self.config.comp_stream is not None:
[1,0]<stderr>:AttributeError: 'Executor' object has no attribute 'config'

Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[56167,1],1]
  Exit code:    1

**Comment by BLue1881euLB** [comment]
已解决，是系统版本的protoc和conda的protoc冲突了
