### ISSUE TITLE
ModuleNotFoundError: No module named 'hetu_cache'

### ISSUE THREAD

**Issue by BLue1881euLB** [Hsword/Hetu#36]
Traceback (most recent call last):
  File "/home/Hetu/examples/ctr/tests/../run_hetu.py", line 200, in <module>
    worker(args)
  File "/home/Hetu/examples/ctr/tests/../run_hetu.py", line 123, in worker
    executor = ht.Executor(eval_nodes, dist_strategy=strategy, cstable_policy=args.cache,
  File "/home/Hetu/python/hetu/gpu_ops/executor.py", line 395, in __init__
    config = HetuConfig(eval_node_list=all_eval_nodes,
  File "/home/Hetu/python/hetu/gpu_ops/executor.py", line 367, in __init__
    topo_sort_with_hook(self.my_eval_nodes, self)
  File "/home/Hetu/python/hetu/gpu_ops/executor.py", line 1319, in topo_sort_with_hook
    topo_sort_dfs_with_hook(node, visited, config)
  File "/home/Hetu/python/hetu/gpu_ops/executor.py", line 1332, in topo_sort_dfs_with_hook
    topo_sort_dfs_with_hook(n, visited, config)
  File "/home/Hetu/python/hetu/gpu_ops/executor.py", line 1333, in topo_sort_dfs_with_hook
    node.forward_hook(config)
  File "/home/Hetu/python/hetu/gpu_ops/ParameterServerCommunicate.py", line 162, in forward_hook
    self.cache = CacheSparseTable(
  File "/home/Hetu/python/hetu/cstable.py", line 27, in __init__
    import hetu_cache
ModuleNotFoundError: No module named 'hetu_cache'

**Comment by Hsword** [comment]
Have you successfully made the hetu-cache module by `make hetu_cache -j 8`?
